export type StoreOption = { value: string; label: string };

export type StoreMeta = {
  slug: string;
  storeId: string;
  label: string;
  areaLabel: string;
  regionLabel: string;
  mapsQueryBase: string;
  brand: "oriental";
};

// Source of truth for store list (38 stores). Slug = storeId without "ol_".
export const STORES: StoreMeta[] = [
  {
    slug: "nagasaki",
    storeId: "ol_nagasaki",
    label: "長崎",
    areaLabel: "長崎・浜んまち",
    regionLabel: "九州・沖縄",
    mapsQueryBase: "長崎 浜町",
    brand: "oriental",
  },
  {
    slug: "fukuoka",
    storeId: "ol_fukuoka",
    label: "福岡",
    areaLabel: "福岡・天神",
    regionLabel: "九州・沖縄",
    mapsQueryBase: "福岡 天神",
    brand: "oriental",
  },
  {
    slug: "kokura",
    storeId: "ol_kokura",
    label: "小倉",
    areaLabel: "北九州・小倉",
    regionLabel: "九州・沖縄",
    mapsQueryBase: "小倉 北九州",
    brand: "oriental",
  },
  {
    slug: "oita",
    storeId: "ol_oita",
    label: "大分",
    areaLabel: "大分",
    regionLabel: "九州・沖縄",
    mapsQueryBase: "大分",
    brand: "oriental",
  },
  {
    slug: "kumamoto",
    storeId: "ol_kumamoto",
    label: "熊本",
    areaLabel: "熊本",
    regionLabel: "九州・沖縄",
    mapsQueryBase: "熊本",
    brand: "oriental",
  },
  {
    slug: "miyazaki",
    storeId: "ol_miyazaki",
    label: "宮崎",
    areaLabel: "宮崎",
    regionLabel: "九州・沖縄",
    mapsQueryBase: "宮崎",
    brand: "oriental",
  },
  {
    slug: "kagoshima",
    storeId: "ol_kagoshima",
    label: "鹿児島",
    areaLabel: "鹿児島",
    regionLabel: "九州・沖縄",
    mapsQueryBase: "鹿児島",
    brand: "oriental",
  },
  {
    slug: "okinawa_ag",
    storeId: "ol_okinawa_ag",
    label: "沖縄AG",
    areaLabel: "沖縄・国際通り",
    regionLabel: "九州・沖縄",
    mapsQueryBase: "沖縄 国際通り",
    brand: "oriental",
  },
  {
    slug: "gangnam",
    storeId: "ol_gangnam",
    label: "ソウル カンナム",
    areaLabel: "韓国・江南",
    regionLabel: "海外",
    mapsQueryBase: "ソウル 江南",
    brand: "oriental",
  },
  {
    slug: "sapporo_ag",
    storeId: "ol_sapporo_ag",
    label: "札幌AG",
    areaLabel: "北海道・札幌",
    regionLabel: "北海道・東北",
    mapsQueryBase: "札幌",
    brand: "oriental",
  },
  {
    slug: "sendai_ag",
    storeId: "ol_sendai_ag",
    label: "仙台AG",
    areaLabel: "宮城・仙台",
    regionLabel: "北海道・東北",
    mapsQueryBase: "仙台",
    brand: "oriental",
  },
  {
    slug: "shibuya",
    storeId: "ol_shibuya",
    label: "渋谷（本店）",
    areaLabel: "東京・渋谷",
    regionLabel: "関東",
    mapsQueryBase: "渋谷",
    brand: "oriental",
  },
  {
    slug: "ebisu",
    storeId: "ol_ebisu",
    label: "恵比寿",
    areaLabel: "東京・恵比寿",
    regionLabel: "関東",
    mapsQueryBase: "恵比寿",
    brand: "oriental",
  },
  {
    slug: "shibuya_ag",
    storeId: "ol_shibuya_ag",
    label: "渋谷AG",
    areaLabel: "東京・渋谷",
    regionLabel: "関東",
    mapsQueryBase: "渋谷",
    brand: "oriental",
  },
  {
    slug: "shinjuku",
    storeId: "ol_shinjuku",
    label: "新宿",
    areaLabel: "東京・新宿",
    regionLabel: "関東",
    mapsQueryBase: "新宿",
    brand: "oriental",
  },
  {
    slug: "ueno",
    storeId: "ol_ueno",
    label: "上野",
    areaLabel: "東京・上野",
    regionLabel: "関東",
    mapsQueryBase: "上野",
    brand: "oriental",
  },
  {
    slug: "ueno_ag",
    storeId: "ol_ueno_ag",
    label: "上野AG",
    areaLabel: "東京・上野",
    regionLabel: "関東",
    mapsQueryBase: "上野",
    brand: "oriental",
  },
  {
    slug: "kashiwa",
    storeId: "ol_kashiwa",
    label: "柏",
    areaLabel: "千葉・柏",
    regionLabel: "関東",
    mapsQueryBase: "柏",
    brand: "oriental",
  },
  {
    slug: "machida",
    storeId: "ol_machida",
    label: "町田",
    areaLabel: "東京・町田",
    regionLabel: "関東",
    mapsQueryBase: "町田",
    brand: "oriental",
  },
  {
    slug: "yokohama",
    storeId: "ol_yokohama",
    label: "横浜",
    areaLabel: "神奈川・横浜",
    regionLabel: "関東",
    mapsQueryBase: "横浜",
    brand: "oriental",
  },
  {
    slug: "omiya",
    storeId: "ol_omiya",
    label: "大宮",
    areaLabel: "埼玉・大宮",
    regionLabel: "関東",
    mapsQueryBase: "大宮 埼玉",
    brand: "oriental",
  },
  {
    slug: "utsunomiya",
    storeId: "ol_utsunomiya",
    label: "宇都宮",
    areaLabel: "栃木・宇都宮",
    regionLabel: "関東",
    mapsQueryBase: "宇都宮",
    brand: "oriental",
  },
  {
    slug: "takasaki",
    storeId: "ol_takasaki",
    label: "高崎",
    areaLabel: "群馬・高崎",
    regionLabel: "関東",
    mapsQueryBase: "高崎",
    brand: "oriental",
  },
  {
    slug: "nagoya_ag",
    storeId: "ol_nagoya_ag",
    label: "名古屋AG",
    areaLabel: "愛知・名古屋",
    regionLabel: "中部",
    mapsQueryBase: "名古屋",
    brand: "oriental",
  },
  {
    slug: "nagoya_nishiki",
    storeId: "ol_nagoya_nishiki",
    label: "名古屋 錦",
    areaLabel: "愛知・名古屋（錦）",
    regionLabel: "中部",
    mapsQueryBase: "名古屋 錦",
    brand: "oriental",
  },
  {
    slug: "nagoya_sakae",
    storeId: "ol_nagoya_sakae",
    label: "名古屋 栄",
    areaLabel: "愛知・名古屋（栄）",
    regionLabel: "中部",
    mapsQueryBase: "名古屋 栄",
    brand: "oriental",
  },
  {
    slug: "shizuoka",
    storeId: "ol_shizuoka",
    label: "静岡",
    areaLabel: "静岡",
    regionLabel: "中部",
    mapsQueryBase: "静岡",
    brand: "oriental",
  },
  {
    slug: "hamamatsu",
    storeId: "ol_hamamatsu",
    label: "浜松",
    areaLabel: "静岡・浜松",
    regionLabel: "中部",
    mapsQueryBase: "浜松",
    brand: "oriental",
  },
  {
    slug: "kanazawa_ag",
    storeId: "ol_kanazawa_ag",
    label: "金沢AG",
    areaLabel: "石川・金沢",
    regionLabel: "中部",
    mapsQueryBase: "金沢",
    brand: "oriental",
  },
  {
    slug: "osaka_ekimae",
    storeId: "ol_osaka_ekimae",
    label: "大阪駅前",
    areaLabel: "大阪・梅田",
    regionLabel: "近畿",
    mapsQueryBase: "大阪駅 梅田",
    brand: "oriental",
  },
  {
    slug: "umeda_ag",
    storeId: "ol_umeda_ag",
    label: "梅田AG",
    areaLabel: "大阪・梅田",
    regionLabel: "近畿",
    mapsQueryBase: "梅田",
    brand: "oriental",
  },
  {
    slug: "tenma",
    storeId: "ol_tenma",
    label: "天満",
    areaLabel: "大阪・天満",
    regionLabel: "近畿",
    mapsQueryBase: "天満",
    brand: "oriental",
  },
  {
    slug: "shinsaibashi",
    storeId: "ol_shinsaibashi",
    label: "心斎橋",
    areaLabel: "大阪・心斎橋",
    regionLabel: "近畿",
    mapsQueryBase: "心斎橋",
    brand: "oriental",
  },
  {
    slug: "namba",
    storeId: "ol_namba",
    label: "難波",
    areaLabel: "大阪・難波",
    regionLabel: "近畿",
    mapsQueryBase: "難波",
    brand: "oriental",
  },
  {
    slug: "kyoto",
    storeId: "ol_kyoto",
    label: "京都",
    areaLabel: "京都・河原町",
    regionLabel: "近畿",
    mapsQueryBase: "京都 河原町",
    brand: "oriental",
  },
  {
    slug: "kobe",
    storeId: "ol_kobe",
    label: "神戸",
    areaLabel: "兵庫・三宮",
    regionLabel: "近畿",
    mapsQueryBase: "神戸 三宮",
    brand: "oriental",
  },
  {
    slug: "okayama",
    storeId: "ol_okayama",
    label: "岡山",
    areaLabel: "岡山",
    regionLabel: "中国・四国",
    mapsQueryBase: "岡山",
    brand: "oriental",
  },
  {
    slug: "hiroshima_ag",
    storeId: "ol_hiroshima_ag",
    label: "広島AG",
    areaLabel: "広島・流川",
    regionLabel: "中国・四国",
    mapsQueryBase: "広島 流川",
    brand: "oriental",
  },
];

export const STORE_OPTIONS: StoreOption[] = STORES.map((s) => ({
  value: s.slug,
  label: s.label,
}));

export const DEFAULT_STORE = STORES[0].slug;

export function getStoreMetaBySlug(slug: string | null | undefined): StoreMeta {
  if (!slug) return STORES[0];
  const normalized = slug.toLowerCase();
  return STORES.find((s) => s.slug === normalized) ?? STORES[0];
}

export function getStoreMetaById(storeId: string | null | undefined): StoreMeta {
  if (!storeId) return STORES[0];
  return STORES.find((s) => s.storeId === storeId) ?? STORES[0];
}
