-- logs: 5分毎の混雑収集データ（全 ML 学習・/api/range 系の唯一の正本、約128万行）
-- 2026-08-22 総合レビュー対応（検証記録は memory/general-review-2026-08-22.md）
--
-- なぜこの migration が今まで無かったか:
--   supabase/migrations/ には blog_drafts 系4本しか無く、最重要資産である logs の
--   スキーマ・インデックスがリポジトリから一切再現できない状態だった（DR上の実穴）。
--
-- このファイルの位置づけ:
--   **本番には既に存在するものを「記録」する migration**。全文 IF NOT EXISTS / 冪等で
--   書いてあるので、現行の本番 DB に対して流しても no-op になる（列追加・型変更等は
--   一切行わない）。将来 DR で空の Supabase プロジェクトから再構築するときに初めて
--   意味を持つ。
--
-- 列定義の根拠（実コードからの復元。本番スキーマとの完全な型一致はオーナー環境の
-- `supabase db pull` でのみ確認できるので、型が確定できない列は妥当な型を推測で
-- 当てている点に注意）:
--   - multi_collect.py の insert_supabase_log() が送る INSERT payload
--     （store_id, ts, men, women, total, src_brand は必須。weather_code/weather_label/
--      temp_c/precip_mm は値が None でないときだけ payload に含める＝NULL 許容）。
--   - oriental/data/provider.py の SELECT 列
--     （select=store_id,ts,men,women,total,weather_code,weather_label,temp_c,precip_mm,src_brand）。
--   - scripts/backup_logs.py の SELECT 列（上記に id を加えたもの。id は
--     `order=id.asc&id=gt.<cursor>` のキーセットページングに使われる一意な整数キー）。
--   - plan/LOGS_BACKUP.md の列挙（id, store_id, ts, men, women, total, weather_code,
--     weather_label, temp_c, precip_mm, src_brand）。
--
-- id は Supabase の標準的な bigint identity 主キーと推測（backup_logs.py が整数として
-- `gt.<cursor>` 比較している一意キーであるため）。real な型（bigint vs bigserial 等）は
-- オーナー環境でのみ確認可能。

create table if not exists public.logs (
  id bigint generated by default as identity primary key,
  ts timestamptz not null,

  store_id text not null,
  -- 'oriental' | 'aisekiya'（multi_collect.py の SUPABASE_BRAND / AISEKIYA_BRAND）。
  -- 型が確定できないため text で妥当推測。
  src_brand text not null default 'oriental',

  men integer not null,
  women integer not null,
  total integer not null,

  -- 天気付随データ。multi_collect.py は取得できた値だけを payload に含めるため NULL 許容。
  weather_code integer,
  weather_label text,
  temp_c double precision,
  precip_mm double precision
);

comment on table public.logs is
  'MEGRIBI 5分毎の混雑収集ログ（全 ML 学習・/api/range 系の唯一の正本）。'
  '列定義はコードからの復元 -- 本番との型の厳密一致はオーナー環境の supabase db pull で確認すること。';

-- 【2026-08事故の教訓・最重要】この2本のインデックスが本番に無かったため、
-- 128万行の全件走査が statement_timeout を越えた瞬間（2026-08-19未明）に
-- 全クエリが57014で死に、収集・表示ともに全停止した
-- （経緯: memory/incident-2026-08-18-recovery.md「第4の事故」）。
-- 当時は Supabase SQL Editor から手動で作成しており、このリポジトリには
-- 一度も記録されていなかった。ここで初めて記録する（本番には適用済み＝no-op）。
create index if not exists logs_store_id_ts_idx on public.logs (store_id, ts desc);
create index if not exists logs_ts_idx on public.logs (ts desc);

-- RLS: このリポジトリの実態（有効化有無・ポリシー内容）は未記録。
-- 推測で書かない。オーナー環境で `supabase db pull` して正本化することを推奨。
